dist: trusty
os: linux
language: java

jdk:
  - openjdk11

cache:
  directories:
    - "$HOME/.m2/repository"
    - "$HOME/.m2/wrapper"

notifications:
  email: false
  slack:
    on_failure: always
    on_success: never
    on_pull_requests: false
    rooms:
      secure: mWzYwXXkaPJ/t24kG9gz6hYyRGoGX+zsjKDa+IzjhY4NeMJyzgHyN3x1vWwSXhfG1jQuBTFyT5RTWN8Jfo2Za/XDKYfMXXP5gCMtNkeWdflYWaUC7sAZepRANUB3gzkCTvkc/DOY/FI07xCcLMJoZ7jGiADNakTaWvzdExJUBs6NuhGdIUmOT+chbip02yN7mSPeqyU7/vFqpCxxEoPeNzaNshLufbZUEWgmLm0bm5Uxdo7Yi5rL0/nA7oqXUzzWTtgQEu0mOG4Oqu7oXAki2rLISw8enZwt5/fUbxGgK1J3UB86vgnDrxbTAhuNUuddaSxUuDsg1+3xyRzU74cyKUWnWqL10Tyy9KgDR0A+48w2v8DH/pOvnvfXA+FL0zLtDJ9jPuSK0dFbceRYmolEGMDF53Q/s2W+waC13Bi3nHRQJKYmT+bOnoLABLpfm5fbV/2br4LVTQwiP80HJ+19Vy4lriF55zu1yjESUBzdvvX1Dhp5E3AXZZv6xB0v4gyZZeOoIv6BxqinLauZiS3nM7O9vu1QnFvbo4HH0Df651fyy1kOU5UAAD+CNRgpZ8GMc+EegvnLbS3nzbNOPlkACmhxMNcpEvD6MomcB4UV2dPWAYIQSfrRV5h+iZlNSqCkA2pl3p6TTZhLMvoSxziRzUZZx7GQe/cnUGN6GbzyyRk=

install: true
script: ./mvnw verify --show-version --batch-mode --no-transfer-progress --errors

before_deploy:
  - ./mvnw clean verify --show-version --batch-mode --no-transfer-progress --errors -Drevision=$TRAVIS_TAG
  - cd $TRAVIS_BUILD_DIR/distribution/target
  - sha256sum artifactory-snyk-security-plugin-$TRAVIS_TAG.zip > artifactory-snyk-security-plugin-$TRAVIS_TAG.zip.sha256
  - cd $TRAVIS_BUILD_DIR
deploy:
  # GitHub releases
  - provider: releases
    api_key:
      secure: Pwh4HEujKVGFKIPvFEAO7mmznvr6Kpwod4Hym9ZsPyAFdV4EMusGk83WKTNXRQCVcbE7B0GS+5y9ruQEWBhXI+rzkF0xZkvApX5V32YpHVUmj2/wwIWs6HQUghoX9dt6ZP+UtljQ1WU5LIlw4fM7xZsyJYPMjL/UFGSDfPZ+SLQ7LNhslLpF2XXMnWF1xhiAYA1Ye4jHp6fEPX2Mf3uoj31bSF0wB90jBf6fGduvEXBxgSnW/UjvmaqMMTT4JaSD+THqjqya0Pk7ia5kiNxOariNeaFxYkIOtwcYJwPSKGrq+6EPPmuFJSJvMNcRRebB304oSIwMWX4hjBesyLQ+u9A7ALOl4xUUIMiQQt0l7R0xjSg1wzZUGyhwCQXKfhITKc5SxK52aVdSJRjACKjDpWYASW926bpO54jCRWyw9PIJVKUYFKU+0BQyKu05Xsdh4DldPnfgCDXVUij2pjHM3tTHjm0QfZtCrKIxljYsuzc4YQK3AcgZ5IBGgPynCVGfHRgwfsyTuW+B0FmURPLC2eAyuxtbxpHQ6r1hgQwYxPrQiVcTjtyNLSB8RNo+z2XU79XC5Ol0VrA8yx4Aa1LHg5COvWMpjS/pWWLeEdniCeRQVOXoshNmUGzqx0Fv0QmD63efpAh2A2TC4y4a9feWQxAuLwwKpupX6GhBRb/qMVs=
    file:
      - distribution/target/artifactory-snyk-security-plugin-$TRAVIS_TAG.zip
      - distribution/target/artifactory-snyk-security-plugin-$TRAVIS_TAG.zip.sha256
    skip_cleanup: true
    on:
      repo: snyk/artifactory-snyk-security-plugin
      tags: true
